# Generated by Django 3.0.8 on 2020-08-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
